### ISSUE TITLE
Remove App Key/Secret from visible in admoin

### ISSUE THREAD

**Issue by broksonic21** [Ayesh/WordPress-oEmbed-Facebook-Instagram#5]
I know the app key/secret need to be saved into wp_options, but it strikes me as less secure that they are visible in cleartext. Should/could those fields (at least the secret) be marked as a password in some way in settings so it's not visible from someone seeing the screen?

**Comment by Ayesh** [comment]
Thanks for opening this, @broksonic21. It was something I was considering as well. I wanted to keep this plugin as minimal as possible, and follow WP core as close as possible too. 

In Settings -> Writing section, there is a "Post via email" section, with a similar password field, and it is in plain text too. I think it helps to keep the API secret field as an open text field because it's easy to spot wrong API keys, given that all API keys are of same length. 

I will mark this ticket closed because it's following what core does. A non-intrusive and light weight, and no-js compatible click-to-reveal option, which otherwise shows a blurred field, for example, would be ideal. Contributions would be welcome of course, and please let me know what do you think.
