### ISSUE TITLE
"disable caption" / "include caption" feature for embedded instagram content

### ISSUE THREAD

**Issue by kozdincer** [Ayesh/WordPress-oEmbed-Facebook-Instagram#9]
Instagram has "disable caption" / "include caption" feature for sharing embedded content.
Can you add this feature to this plugin?

You can see the SS below when want to get embedded code from the web version of Instagram.
![image](https://user-images.githubusercontent.com/914386/99788220-d90f9100-2b31-11eb-8933-7c14efc177d9.png)

**Comment by Ayesh** [comment]
Hi @kozdincer thanks for opening this. 

Do you know if there's an oEmbed API parameter to get this same output?

**Comment by kozdincer** [comment]
I see "hidecaption" in documentation. Is this what you mention to? @Ayesh 
https://developers.facebook.com/docs/graph-api/reference/instagram-oembed

**Comment by Ayesh** [comment]
You are right, the API document indeed mention it and that looks like the URL we are looking at. 

For the moment, I think this falls out of the original scope of the plugin. Facebook was going to drop support for unauthenticated oEmbeds, and I wanted to fill in the gap. I don't think any other oEmbed provider supports additional features, and they are not incorporated to the embed UI either. The fact that both classic editor and block editor use same APIs makes it a bit more complicated too. 

I will close this issue now, because I personally wouldn't be able to work on this feature due to time constraints and because I believe it falls out of the original scope. I would be happy to review any contributions. For a more sophisticated oEmbeds that has specific features for each provider, I think a different plugin might be more fitting. 

Thank you.
